# Application Secrets Configuration
# WARNING: This file contains sensitive information

database:
  host: prod-db.secureshop.internal
  username: admin
  password: Pr0duct!onDB_2024
  port: 5432

api_keys:
  google_maps: AIzaSyBx1234567890abcdefghijklmnopqrstuvw
  sendgrid: SG.KzJ8x9YwT2abcdefghijklmnop.xyz789abcdefghijklmnopqrstuvwxyz123
  twilio:
    account_sid: ACabcdef1234567890ghijklmnopqrstuv
    auth_token: abcdef1234567890ghijklmnopqrstuv
  
oauth:
  github:
    client_id: Iv1.a1b2c3d4e5f6g7h8
    client_secret: abcdef1234567890ghijklmnopqrstuvwxyz12345
  google:
    client_id: 123456789012-abcdefghijklmnopqrstuvwxyz.apps.googleusercontent.com
    client_secret: GOCSPX-abcdefghijklmnopqrs
  
jwt:
  secret: super-secret-jwt-key-that-should-be-random-12345
  refresh_secret: another-secret-key-for-refresh-tokens-67890
  expiry: 3600

aws:
  access_key_id: AKIAIOSFODNN7EXAMPLE
  secret_access_key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  region: eu-west-2

encryption:
  master_key: ZmDfcTF7_60GrrY167zsiPd67pEvs0aGOv2oasOM1Pg=
  algorithm: aes-256-gcm

internal_services:
  payment_api: http://10.0.1.52:3000
  user_api: http://10.0.1.53:3000
  admin_panel: http://10.0.1.100:8080
  
admin:
  username: admin
  password: Admin123!
  email: admin@secureshop.com
  api_key: admin_api_key_xyz789abc123
